import type { Product } from '../../types/portalTypes';

export const CATALOG_PRODUCTS: Product[] = [
  {
    slug: 'flights',
    name: 'Flights',
    icon: 'Plane',
    shortDescription: 'Flight bookings and upgrades',
    fullDescription: 'Offer your customers access to a comprehensive flight booking engine with real-time availability, competitive pricing, and instant confirmation. The Flights product supports round-trip, one-way, and multi-city itineraries across a global network of airlines. Integration includes seat selection, class upgrades, and ancillary services.',
    benefits: [
      { icon: 'Globe', title: 'Global Coverage', description: 'Access to 1,000+ airlines worldwide with real-time availability and pricing' },
      { icon: 'DollarSign', title: 'Revenue Generation', description: 'Earn commission on every booking with transparent pricing models' },
      { icon: 'Zap', title: 'Real-time Booking', description: 'Instant confirmation with live inventory management' },
    ],
    integrationGuide: 'Integrate flight search and booking via the /flights/search and /flights/book endpoints. Requires passenger details, route information, and payment authorization. Supports both one-way and round-trip queries with flexible date matching.',
    documentationUrl: 'https://docs.dragonpass.com/flights',
    clientStatus: 'active',
    unitCostGBP: 85.00,
  },
  {
    slug: 'hotels',
    name: 'Hotels',
    icon: 'Building2',
    shortDescription: 'Hotel reservations and room upgrades',
    fullDescription: 'Provide premium hotel booking capabilities with access to a curated portfolio of properties worldwide. The Hotels product supports standard reservations, room upgrades, and special rate programs. Integration includes property search, room availability, rate comparison, and booking management with real-time confirmation.',
    benefits: [
      { icon: 'Star', title: 'Premium Properties', description: 'Curated portfolio of 500,000+ hotels from luxury to boutique' },
      { icon: 'TrendingUp', title: 'Dynamic Pricing', description: 'Best available rates with member-exclusive discounts' },
      { icon: 'Shield', title: 'Secure Booking', description: 'PCI-compliant payment processing with instant confirmation' },
    ],
    integrationGuide: 'Use /hotels/search for property discovery with location, date, and guest parameters. Complete bookings via /hotels/book with room selection and guest details. Supports modification and cancellation flows.',
    documentationUrl: 'https://docs.dragonpass.com/hotels',
    clientStatus: 'payg',
    unitCostGBP: 65.00,
  },
  {
    slug: 'airport-lounge',
    name: 'Airport Lounge',
    icon: 'Sofa',
    shortDescription: 'Premium airport lounge access',
    fullDescription: 'Give your customers access to a global network of premium airport lounges. The Airport Lounge product provides digital pass generation, real-time availability checking, and capacity management across 1,300+ lounges in 650+ cities. Supports single-use passes, membership programs, and guest access.',
    benefits: [
      { icon: 'Globe', title: '1,300+ Lounges', description: 'Global network spanning 650+ cities and 180+ countries' },
      { icon: 'Smartphone', title: 'Digital Passes', description: 'QR-code based entry with real-time validation' },
      { icon: 'Users', title: 'Guest Access', description: 'Support for companion and family passes' },
    ],
    integrationGuide: 'Search available lounges via /lounges/search using airport code and terminal. Issue digital passes with /lounges/passes/create. Supports real-time capacity checks and guest pass additions.',
    documentationUrl: 'https://docs.dragonpass.com/lounges',
    clientStatus: 'active',
    unitCostGBP: 25.00,
  },
  {
    slug: 'airport-transfer',
    name: 'Airport Transfer',
    icon: 'Car',
    shortDescription: 'Ground transportation services',
    fullDescription: 'Offer door-to-door ground transportation between airports and destinations. The Airport Transfer product supports sedan, SUV, van, and luxury vehicle classes with real-time driver tracking, flight monitoring, and automated pickup coordination. Covers arrivals, departures, and inter-terminal transfers.',
    benefits: [
      { icon: 'MapPin', title: 'Door-to-Door', description: 'Seamless transfers between airport and any destination' },
      { icon: 'Clock', title: 'Flight Tracking', description: 'Automated pickup adjustment based on real-time flight status' },
      { icon: 'Car', title: 'Vehicle Options', description: 'Sedan, SUV, van, and luxury vehicle classes available' },
    ],
    integrationGuide: 'Get quotes via /transfers/quote with pickup/dropoff coordinates and vehicle class. Book transfers with /transfers/book. Track active transfers via /transfers/{id}/status for real-time driver location.',
    documentationUrl: 'https://docs.dragonpass.com/transfers',
    clientStatus: 'active',
    unitCostGBP: 45.00,
  },
  {
    slug: 'airport-dining',
    name: 'Airport Dining',
    icon: 'UtensilsCrossed',
    shortDescription: 'Airport restaurant reservations',
    fullDescription: 'Enable your customers to discover and reserve tables at airport restaurants and dining venues. The Airport Dining product supports table reservations, pre-ordering, and digital voucher management across partner restaurants in major airports worldwide.',
    benefits: [
      { icon: 'UtensilsCrossed', title: 'Restaurant Network', description: 'Partner restaurants across 200+ major airports' },
      { icon: 'Clock', title: 'Pre-Order', description: 'Customers can order ahead to minimize wait times' },
      { icon: 'CreditCard', title: 'Digital Vouchers', description: 'Cashless dining experience with digital payment' },
    ],
    integrationGuide: 'Search dining options via /dining/search using airport code. Create reservations with /dining/reserve. Supports voucher-based payment via /dining/vouchers/create.',
    documentationUrl: 'https://docs.dragonpass.com/dining',
    clientStatus: 'available',
    unitCostGBP: 30.00,
  },
  {
    slug: 'fast-track',
    name: 'Airport Fast Track',
    icon: 'Zap',
    shortDescription: 'Priority security and immigration',
    fullDescription: 'Provide priority passage through airport security and immigration checkpoints. The Fast Track product offers digital pass generation for expedited processing at participating airports, reducing wait times and improving the travel experience.',
    benefits: [
      { icon: 'Zap', title: 'Skip the Queue', description: 'Priority access to security and immigration lanes' },
      { icon: 'Smartphone', title: 'Digital Pass', description: 'QR-code based entry for seamless validation' },
      { icon: 'Clock', title: 'Time Savings', description: 'Average 30-minute reduction in airport processing time' },
    ],
    integrationGuide: 'Check availability via /fast-track/availability with airport code and date. Issue passes with /fast-track/passes/create. Supports group bookings and return journey passes.',
    documentationUrl: 'https://docs.dragonpass.com/fast-track',
    clientStatus: 'active',
    unitCostGBP: 18.00,
  },
  {
    slug: 'esims',
    name: 'eSIMs',
    icon: 'Smartphone',
    shortDescription: 'International mobile connectivity',
    fullDescription: 'Offer your customers affordable international mobile connectivity through eSIM technology. The eSIMs product provides instant digital SIM provisioning with data-only and voice+data plans across 190+ countries. No physical SIM swap required — customers activate directly on their compatible device.',
    benefits: [
      { icon: 'Globe', title: '190+ Countries', description: 'Coverage across virtually every international destination' },
      { icon: 'Zap', title: 'Instant Activation', description: 'Digital provisioning with no physical SIM needed' },
      { icon: 'DollarSign', title: 'Cost Effective', description: 'Up to 90% savings vs. traditional roaming charges' },
    ],
    integrationGuide: 'List available plans via /esims/plans with destination country. Purchase and provision eSIMs with /esims/provision. Check usage via /esims/{id}/usage. Supports top-up via /esims/{id}/topup.',
    documentationUrl: 'https://docs.dragonpass.com/esims',
    clientStatus: 'active',
    unitCostGBP: 12.50,
  },
  {
    slug: 'tickets',
    name: 'Tickets',
    icon: 'Ticket',
    shortDescription: 'Event and entertainment tickets',
    fullDescription: 'Enable event and entertainment ticket discovery and booking for your customers. The Tickets product covers concerts, sports events, theatre, attractions, and experiences across major cities worldwide. Integration includes event search, seat selection, and digital ticket delivery.',
    benefits: [
      { icon: 'Calendar', title: 'Live Events', description: 'Access to concerts, sports, theatre, and attractions worldwide' },
      { icon: 'Smartphone', title: 'Digital Tickets', description: 'Mobile ticket delivery with QR-code venue entry' },
      { icon: 'Star', title: 'Premium Seats', description: 'VIP and premium seating options for exclusive experiences' },
    ],
    integrationGuide: 'Search events via /tickets/search with location and date filters. View seating options with /tickets/{eventId}/seats. Book tickets via /tickets/book with seat selection and attendee details.',
    documentationUrl: 'https://docs.dragonpass.com/tickets',
    clientStatus: 'available',
    unitCostGBP: 22.00,
  },
  {
    slug: 'health-wellness',
    name: 'Health & Wellness',
    icon: 'Heart',
    shortDescription: 'Spa and wellness services',
    fullDescription: 'Offer spa, wellness, and health services to your customers at airports and partner locations. The Health & Wellness product covers spa treatments, fitness facilities, sleep pods, and medical services with integrated booking and payment.',
    benefits: [
      { icon: 'Heart', title: 'Wellness Network', description: 'Spa, fitness, and wellness venues at major airports' },
      { icon: 'Clock', title: 'Flexible Booking', description: 'Real-time availability with flexible scheduling' },
      { icon: 'Star', title: 'Premium Services', description: 'Curated treatments and wellness experiences' },
    ],
    integrationGuide: 'Search services via /wellness/search with airport code and service type. Book treatments with /wellness/book. Supports cancellation and rescheduling via /wellness/{id}/modify.',
    documentationUrl: 'https://docs.dragonpass.com/wellness',
    clientStatus: 'available',
    unitCostGBP: 35.00,
  },
];
