import type { Entitlement } from '../../types/portalTypes';

// A client can hold several membership templates, and the categories a
// swappable point covers vary between them.
export interface SwappableMembership {
  code: string;
  entitlements: number;
  eligible: string[];
}

export const SWAPPABLE_MEMBERSHIPS: Record<'test' | 'production', SwappableMembership[]> = {
  // Test carries a template covering every Dragonpass category, to show how a
  // full eligible list behaves in the table.
  test: [
    {
      code: 'MBR-100244',
      entitlements: 12,
      eligible: [
        'airport-lounge', 'fast-track', 'airport-dining', 'airport-transfer',
        'flights', 'hotels', 'esims', 'tickets', 'health-wellness',
      ],
    },
    { code: 'MBR-100871', entitlements: 4, eligible: ['airport-lounge', 'fast-track'] },
    { code: 'MBR-101396', entitlements: 6, eligible: ['airport-dining', 'esims', 'tickets'] },
  ],
  production: [
    { code: 'MBR-004821', entitlements: 5, eligible: ['airport-lounge', 'airport-dining', 'fast-track'] },
    { code: 'MBR-007163', entitlements: 3, eligible: ['airport-lounge', 'airport-dining'] },
    { code: 'MBR-012094', entitlements: 8, eligible: ['airport-dining', 'fast-track'] },
  ],
};

export const MOCK_ENTITLEMENTS: Entitlement[] = [
  {
    id: 'ent-swap-test',
    productSlug: 'swappable',
    productName: 'Swappable Product',
    productIcon: 'Shuffle',
    description: 'Flexible benefit credits redeemable across different products',
    environment: 'test',
    benefitType: 'entitlement',
    unitCostGBP: 20.00,
    allocation: 2500,
    used: 900,
    remaining: 1600,
    cap: 2500,
    status: 'active',
    alertThresholds: { enabled: false, thresholds: [80, 90], recipients: [] },
    lastAlertedThreshold: null,
    startDate: '2026-01-15',
    endDate: '2026-12-31',
    createdAt: '2026-01-15',
    updatedAt: '2026-09-18',
  },
  {
    id: 'ent-swap-prod',
    productSlug: 'swappable',
    productName: 'Swappable Product',
    productIcon: 'Shuffle',
    description: 'Flexible benefit credits redeemable across different products',
    environment: 'production',
    benefitType: 'entitlement',
    unitCostGBP: 20.00,
    allocation: 6000,
    used: 2400,
    remaining: 3600,
    cap: 6000,
    status: 'active',
    alertThresholds: { enabled: true, thresholds: [80, 90], recipients: ['admin@example.com'] },
    lastAlertedThreshold: null,
    startDate: '2026-01-15',
    endDate: '2026-12-31',
    createdAt: '2026-01-15',
    updatedAt: '2026-09-18',
  },
  {
    id: 'ent-1',
    productSlug: 'esims',
    productName: 'eSIMs',
    productIcon: 'Smartphone',
    description: 'International mobile connectivity',
    environment: 'test',
    benefitType: 'entitlement',
    unitCostGBP: 12.50,
    allocation: 1000,
    used: 347,
    remaining: 653,
    cap: 1000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [80, 90],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: null,
    startDate: '2026-01-15',
    endDate: '2026-12-31',
    createdAt: '2026-01-15',
    updatedAt: '2026-03-17',
  },
  {
    id: 'ent-2',
    productSlug: 'airport-lounge',
    productName: 'Airport Lounge',
    productIcon: 'Sofa',
    description: 'Premium airport lounge access',
    environment: 'test',
    benefitType: 'entitlement',
    unitCostGBP: 25.00,
    allocation: 20000,
    used: 17450,
    remaining: 2550,
    cap: 20000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [80, 90],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: 80,
    startDate: '2026-01-15',
    createdAt: '2026-01-15',
    updatedAt: '2026-03-17',
  },
  {
    id: 'ent-3',
    productSlug: 'airport-transfer',
    productName: 'Airport Transfer',
    productIcon: 'Car',
    description: 'Ground transportation services',
    environment: 'production',
    benefitType: 'discount',
    discountPercent: 15,
    unitCostGBP: 45.00,
    allocation: 5000,
    used: 1230,
    remaining: 3770,
    cap: null,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [80, 90],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: null,
    startDate: '2026-01-15',
    createdAt: '2026-01-15',
    updatedAt: '2026-03-17',
  },
  {
    id: 'ent-4',
    productSlug: 'airport-lounge',
    productName: 'Airport Lounge',
    productIcon: 'Sofa',
    description: 'Premium airport lounge access',
    environment: 'production',
    benefitType: 'entitlement',
    unitCostGBP: 25.00,
    allocation: 15000,
    used: 13200,
    remaining: 1800,
    cap: 15000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [80, 90],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: 80,
    startDate: '2026-01-15',
    endDate: '2027-01-15',
    createdAt: '2026-01-15',
    updatedAt: '2026-03-20',
  },
  {
    id: 'ent-5',
    productSlug: 'fast-track',
    productName: 'Airport Fast Track',
    productIcon: 'Zap',
    description: 'Priority security and immigration lanes',
    environment: 'production',
    benefitType: 'entitlement',
    unitCostGBP: 18.00,
    allocation: 8000,
    used: 8000,
    remaining: 0,
    cap: 8000,
    status: 'exhausted',
    alertThresholds: {
      enabled: true,
      thresholds: [80, 90],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: 100,
    startDate: '2026-01-15',
    endDate: '2026-06-30',
    createdAt: '2026-01-15',
    updatedAt: '2026-03-22',
  },
  {
    id: 'ent-6',
    productSlug: 'esims',
    productName: 'eSIMs',
    productIcon: 'Smartphone',
    description: 'International mobile connectivity',
    environment: 'production',
    benefitType: 'discount',
    discountPercent: 20,
    unitCostGBP: 12.50,
    allocation: 2000,
    used: 480,
    remaining: 1520,
    cap: null,
    status: 'active',
    alertThresholds: {
      enabled: false,
      thresholds: [],
      recipients: [],
    },
    lastAlertedThreshold: null,
    startDate: '2026-02-01',
    createdAt: '2026-02-01',
    updatedAt: '2026-03-18',
  },
  {
    id: 'ent-7',
    productSlug: 'flights',
    productName: 'Flights',
    productIcon: 'Plane',
    description: 'Flight bookings and upgrades',
    environment: 'production',
    benefitType: 'entitlement',
    unitCostGBP: 85.00,
    allocation: 3000,
    used: 910,
    remaining: 2090,
    cap: 3000,
    status: 'active',
    alertThresholds: {
      enabled: true,
      thresholds: [80, 90],
      recipients: ['admin@example.com'],
    },
    lastAlertedThreshold: null,
    startDate: '2026-02-15',
    createdAt: '2026-02-15',
    updatedAt: '2026-03-10',
  },
];
